---

- name: Power off VM
  block:
    - name: Set the state of a virtual machine to poweroff
      community.vmware.vmware_guest_powerstate:
        hostname: "{{vcenter.hostname}}"
        username: "{{ vcenter.username }}"
        password: "{{ vcenter.password }}"
        folder: "{{vcenter.folder}}"
        name: "{{vcenter.vmname}}"
        validate_certs: False
        state: powered-off
      delegate_to: localhost
      register: deploy

    - name: Delete vSphere VM
      vmware_guest:
        hostname: "{{vcenter.hostname}}"
        username: "{{vcenter.username}}"
        password: "{{vcenter.password}}"
        validate_certs: False
        name: "{{vcenter.vmname}}"
        datacenter: "{{vcenter.datacenter}}"
        folder: "{{vcenter.folder}}"
        state: absent
        force: True

    - name: Delete PK
      community.vmware.vsphere_file:
        hostname: "{{vcenter.hostname}}"
        username: "{{vcenter.username}}"
        password: "{{vcenter.password}}"
        datacenter: "{{vcenter.datacenter}}"
        datastore: "{{vcenter.datastore}}"
        path: "{{vcenter.vmname}}/PK.cer"
        state: absent
        validate_certs: no
      delegate_to: localhost

    - name: Delete KEK
      community.vmware.vsphere_file:
        hostname: "{{vcenter.hostname}}"
        username: "{{vcenter.username}}"
        password: "{{vcenter.password}}"
        datacenter: "{{vcenter.datacenter}}"
        datastore: "{{vcenter.datastore}}"
        path: "{{vcenter.vmname}}/KEK.cer"
        state: absent
        validate_certs: no
      delegate_to: localhost

    - name: Delete DB
      community.vmware.vsphere_file:
        hostname: "{{vcenter.hostname}}"
        username: "{{vcenter.username}}"
        password: "{{vcenter.password}}"
        datacenter: "{{vcenter.datacenter}}"
        datastore: "{{vcenter.datastore}}"
        path: "{{vcenter.vmname}}/DB.cer"
        state: absent
        validate_certs: no
      delegate_to: localhost

    - name: Delete a VM folder on given datacenter
      community.vmware.vcenter_folder:
        hostname: "{{vcenter.hostname}}"
        username: "{{vcenter.username}}"
        password: "{{vcenter.password}}"
        datacenter_name: "{{vcenter.datacenter}}"
        folder_name: "{{vcenter.vmname}}"
        validate_certs: False
        folder_type: vm
        state: absent
      register: vm_folder_deletion_result
      delegate_to: localhost